config/routes.rb
Rails.application.routes.draw do
  resources :samples
  mount Ckeditor::Engine => '/ckeditor'
  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  jinda_methods = ['pending','status','search','doc','logs','ajax_notice']
  jinda_methods += ['init','run','run_do','run_form','end_form']
  jinda_methods.each do |aktion| get "/jinda/#{aktion}" => "jinda##{aktion}" end
  # get jinda method routes
  post '/jinda/pending' => 'jinda#index'
  post '/jinda/end_form' => 'jinda#end_form'
  get '/articles/my' => 'articles/my'
  resources :articles
  resources :identities
  resources :sessions
  resources :password_resets
  resources :jinda, :only => [:index, :new]
  root :to => 'jinda#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample
  include Mongoid::Document
  field :title, type: String
  field :item, type: String
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:title, :item)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.haml
= form_for @sample do |f|
  - if @sample.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sample.errors.count, "error")} prohibited this sample from being saved:"
      %ul
        - @sample.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :item
    = f.text_field :item
  .actions
    = f.submit 'Save'

app/views/samples/edit.html.haml
%h1 Editing sample

= render 'form'

= link_to 'Show', @sample
\|
= link_to 'Back', samples_path

app/views/samples/index.html.haml
%h1 Listing samples

%table
  %thead
    %tr
      %th Title
      %th Item
      %th
      %th
      %th

  %tbody
    - @samples.each do |sample|
      %tr
        %td= sample.title
        %td= sample.item
        %td= link_to 'Show', sample
        %td= link_to 'Edit', edit_sample_path(sample)
        %td= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Sample', new_sample_path

app/views/samples/new.html.haml
%h1 New sample

= render 'form'

= link_to 'Back', samples_path

app/views/samples/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @sample.title
%p
  %b Item:
  = @sample.item

= link_to 'Edit', edit_sample_path(@sample)
\|
= link_to 'Back', samples_path